version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: oreo-db
    restart: always
    environment:
      POSTGRES_USER: oreo
      POSTGRES_PASSWORD: oreo123
      POSTGRES_DB: oreodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: oreo-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@oreo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
